version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: skystats
    main: ./core
    binary: skystats
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids: [skystats]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:

changelog:
  use: github

release:
  draft: false
  prerelease: auto
  make_latest: auto
